### ISSUE TITLE
Windows RT not booting

### ISSUE THREAD

**Issue by xerix123456** [HTC-Leo-Revival-Project/HtcLeoPkg#33]
when i try to boot windows rt from microsd card, it just hangs on the logo. i can see that windows boot manager is working because it displayed an error when i removed efi/microsoft/boot/bcd

**Comment by Dominduchami** [comment]
Windows RT doesn't have inbox support for vectored interrupt controller & timer found on hd2, so currently it's not bootable past bootmgr (and almost definitely won't ever be)

**Comment by binarymaster** [comment]
@xerix123456 if you can do a HAL extension, or patch Windows HAL, you should be able to do this.

**Comment by J0SH1X** [comment]
Closing for now with wont fix.

We need proper sdcard Support on htc nexus one first, it has uart Support unlike leo and desire
